name: aurora 39
on:
  merge_group:
  pull_request:
    branches:
      - main
      - testing
    paths-ignore:
      - '**.md'
      - 'system_files/cosmic/**'
  push:
    branches:
      - main
      - testing
    paths-ignore:
      - '**.md'
      - 'system_files/cosmic/**'
  schedule:
    - cron: '41 16 * * *'  # 16:41 UTC everyday
  workflow_dispatch:

jobs:
  build:
    name: build
    uses: ./.github/workflows/reusable-build.yml
    secrets: inherit
    with:
      brand_name: stellar
      fedora_version: 39